src/buyandsell/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views
# from cart import views as cart_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('core.urls')),
    path('cart2/', include('cart2.urls')),
    path('', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart2/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart2'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

src/core/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('create/', ProductCreateView.as_view(), name="product-create"),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name="product-update"),
    path('<int:pk>/delete', ProductDeleteView.as_view(), name="product-delete"),
    path('<int:pk>/', ProductDetailView.as_view(), name="product-detail"),
]

src/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^process-payment/', views.process_payment, name='process_payment'),
    url(r'^payment_done/', views.payment_done, name='payment_done'),
    url(r'^payment_cancelled/', views.payment_cancel, name='payment_concelled'),

]

src/shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name="product_list"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)$', views.product_detail, name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name="product_list_by_category"),
]

src/cart2/models.py
from django.db import models

# Create your models here.

src/cart2/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/cart2/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Item
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):    
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    print(product)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])

    return redirect('cart2:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    cart.remove(product)

    return redirect('cart2:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial= {
            'quantity': item['quantity'],
            'update': True

        })

    return render(request, 'cart2/detail.html', {
        'cart': cart
    })

src/cart2/templates/cart2/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping cart
{% endblock  %}
{% block content %}

<div class="container">
    <div class="row" style="margin-top: 6%;">
        <h2>Your Shopping Cart <span class="badge pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My shopping order:
                    <a href=" {% url "cart2:cart_detail" %} " style="color: #ffffff;">
                        {{ totail_items }} item {{ totail_items|pluralize }}, Rs. {{ cart.get_total_price }}
                    </a>

                {% else %}
                    <p>Your cart is empty</p>
                {% endif %}

            {% endwith %}

        </span> </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA;">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unity Price</th>
                    <th>Price</th>
                </tr>

            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="../{% if product.image %}{{product.image.url }}{% else %} {% static 'img/default.jpg' %} {% endif%} " alt="product-img" style="height: 130px; width: auto">
                            </a>

                        </td>
                        <td>
                            {{ product.name }}
                        </td>
                        <td> <form action=" {% url 'cart2:cart_add' product.id %} " method="POST">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update" class="btn btn-info">

                        </form> 
                        </td>
                        <td>
                            <a href=" {% url 'cart2:cart_remove' product.id %} ">Remove</a>
                        </td>
                        <td> Rs. {{ item.price }} </td>
                        <td> Rs. {{ item.total_price }} </td>
                    </tr>
                        
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA;">
                    <td> <b> Total </b> </td>
                    <td colspan="4"></td>
                    <td colspan="num"> Rs. {{ cart.get_total_price }} </td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href=" {% url 'shop:product_list' %} " class="btn btn-default">Continue Shopping</a>
            <a href=" {% url 'orders:order_create' %} " class="btn btn-primary">Checkout </a>
        </p>


    </div>
</div>



{% endblock  %}