src/buyandsell/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views
# from cart import views as cart_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('core.urls')),
    path('cart2/', include('cart2.urls')),
    path('', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart2/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart2'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

src/core/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('create/', ProductCreateView.as_view(), name="product-create"),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name="product-update"),
    path('<int:pk>/delete', ProductDeleteView.as_view(), name="product-delete"),
    path('<int:pk>/', ProductDetailView.as_view(), name="product-detail"),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} welcome to ShoppingApp {% endblock %} </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                <a class="navbar-brand" href="#" class="navbar-brand">SmartShopping</a>
            </div>
            <div class="collapse navbar-collapse" id="#bs-example-navbar-collapse-1">            
                <ul class="nav navbar-nav">
                    <li class="active"> <a href="#">Home</a> </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        {% if user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> {{ request.user.name }} <b class="caret"></b> </a>
                            <ul class="dropdown-menu">
                                <li> <a href=""> logout </a> </li>
                        {% endif %}
                                <li class="divider"></li>
                                <li>SignIn</li>
                                <li>SignUp</li>
                            </ul>
                        
                    </li>

                </ul>
            </div>
        </div>

    </nav>
    <div class="container">
        <div class="row" style="margin-top: 6%;">
            <button class="btn btn-info pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My shopping order:
                        <a href=" {% url "cart2:cart_detail" %} " style="color: #ffffff;">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Rs. {{ cart.get_total_price }}
                        </a>

                    {% else %}
                        <p>Your cart is empty</p>
                    {% endif %}

                {% endwith %}
            </button>
        </div>        
    </div>
    {% block content %}
                
    {% endblock %}    
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>